apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
spec:
  syncPolicy:
    automated: {}
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: apps
    repoURL: 'https://github.com/FrengerH/cluster'
    targetRevision: HEAD
  project: default

