---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-photos
  nfs:
    server: <path:nas-config#domain>
    path: /photos
  mountOptions:
    - vers=3
    - nolock

---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-pvc
spec:
  storageClassName: nfs-photos
  volumeName: photos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
