image:
  repository: lscr.io/linuxserver/lidarr
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  main:
    enabled: true
    primary: true
    ingressClassName: traefik

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

    hosts: 
      - host: <path:lidarr-config#domain>
        paths:
          - path: /
            pathType: ImplementationSpecific

    tls:
      - hosts:
          - <path:lidarr-config#domain>
        secretName: tls-lidarr-ingress

env:
  TZ: Europe/Amsterdam
  PUID: '1000'
  PGID: '1003'

persistence:
  config:
    enabled: true
    size: 10Gi
    storageClass: longhorn
    accessMode: ReadWriteOnce
  media:
    enabled: true
    existingClaim: media-pvc

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1003
  fsGroup: 1003
