apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  template:
    spec:
      initContainers:
      - name: create-git-directory
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - mkdir -p /home/node/.n8n-files/git && chown -R 1000:1000 /home/node/.n8n-files
        volumeMounts:
        - name: node-modules
          mountPath: /home/node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-worker
spec:
  template:
    spec:
      initContainers:
      - name: create-git-directory
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - mkdir -p /home/node/.n8n-files/git && chown -R 1000:1000 /home/node/.n8n-files
        volumeMounts:
        - name: data
          mountPath: /home/node
