apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: n8n-websocket
  namespace: n8n
spec:
  headers:
    customRequestHeaders:
      Connection: "keep-alive, Upgrade"
      Upgrade: "WebSocket"
