ingress:
  main:
    enabled: true
    primary: true
    ingressClassName: traefik

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

    hosts: 
      - host: <path:radarr-config#domain>
        paths:
          - path: /
            pathType: ImplementationSpecific

    tls:
      - hosts:
          - <path:radarr-config#domain>
        secretName: tls-radarr-ingress

env:
  # -- Set the timezone that will be used by the container
  TZ: Europe/Amsterdam
  # -- Set the user ID that the container will run Prowlarr as
  PUID: '1000'
  # -- Set the group ID that the container will run Prowlarr as
  PGID: '1003'

persistence:
  config:
    enabled: true
    size: 10Gi
    storageClass: longhorn
    accessMode: ReadWriteOnce
  media:
    enabled: true
    size: 150Gi
    storageClass: nfs-media
    accessMode: ReadWriteOnce
