---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
  namespace: unifi
spec:
  commonName: <path:unifi-config#domain>
  secretName: unifi-cert
  dnsNames:
    - <path:unifi-config#domain>
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
