---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: unifi
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: unifi
subsets:
- addresses:
  - ip: 192.168.123.1
  ports:
  - port: 443
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: unifi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  ingressClassName: traefik
  rules:
  - host: <path:unifi-config#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi
            port:
              number: 443
  tls:
  - hosts:
    - <path:unifi-config#domain>
    secretName: tls-unifi-ingress
