apiVersion: v1
kind: Secret
metadata:
  name: alpine-vm-cloud-init
  namespace: kubevirt
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: alpine-vm
    manage_etc_hosts: true
    users:
      - name: alpine
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
          - <path:dev-config#ssh-key1>
    package_update: true
    package_upgrade: true
    runcmd:
      - dnf update -y
      - dnf install -y openssh-server
      - systemctl enable --now sshd
      - sed -i 's/#PermitRootLogin.*/PermitRootLogin no/g' /etc/ssh/sshd_config.d/50-redhat.conf /etc/ssh/sshd_config
      - sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/g' /etc/ssh/sshd_config.d/50-redhat.conf /etc/ssh/sshd_config
      - firewall-cmd --permanent --add-service=ssh
      - firewall-cmd --reload
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: alpine-vm
  namespace: kubevirt
  labels:
    app: alpine-vm
spec:
  domain:
    cpu:
      cores: 2
    memory:
      guest: 4Gi
    features:
      acpi: {}
      apic: {}
    firmware:
      bootloader:
        efi:
          secureBoot: false
    devices:
      disks:
      - name: rootdisk
        disk:
          bus: virtio
      - name: cloudinit
        cdrom:
          bus: scsi
      interfaces:
      - name: default
        masquerade: {}
  networks:
  - name: default
    pod: {}
  volumes:
  - name: rootdisk
    containerDisk:
      image: docker.io/containercraft/fedora:42
  - name: cloudinit
    cloudInitNoCloud:
      secretRef:
        name: alpine-vm-cloud-init
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-ssh
  namespace: kubevirt
spec:
  type: LoadBalancer
  selector:
    app: alpine-vm
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
