apiVersion: v1
kind: Secret
metadata:
  name: alpine-vm-cloud-init
  namespace: kubevirt
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: alpine-vm
    manage_etc_hosts: true
    users:
      - name: ferry
        shell: /bin/sh
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7eeqvAb4TGa0E033ml1m5YtwalDMqxwAfBbdG0HW7G ferry@alpine-vm
    package_update: true
    package_upgrade: true
    packages:
      - openssh-server
      - sudo
    runcmd:
      - rc-update add sshd default
      - /etc/init.d/sshd start
      - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
      - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
      - /etc/init.d/sshd restart
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: alpine-dv
  namespace: kubevirt
spec:
  source:
    http:
      url: "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/cloud/generic_alpine-3.20.0-aarch64-uefi-cloudinit-r0.qcow2"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: alpine-vm
  namespace: kubevirt
  labels:
    app: alpine-vm
spec:
  domain:
    cpu:
      cores: 1
      model: host-passthrough
    memory:
      guest: 512Mi
    devices:
      disks:
      - name: rootdisk
        disk:
          bus: virtio
      - name: cloudinit
        cdrom: {}
      interfaces:
      - name: default
        masquerade: {}
  networks:
  - name: default
    pod: {}
  volumes:
  - name: rootdisk
    dataVolume:
      name: alpine-dv
  - name: cloudinit
    cloudInitNoCloud:
      secretRef:
        name: alpine-vm-cloud-init
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-ssh
  namespace: kubevirt
spec:
  type: LoadBalancer
  selector:
    app: alpine-vm
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
