apiVersion: v1
kind: Secret
metadata:
  name: ubuntu-vm-cloud-init
  namespace: kubevirt
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: ubuntu-vm
    manage_etc_hosts: true
    users:
      - name: ferry
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7eeqvAb4TGa0E033ml1m5YtwalDMqxwAfBbdG0HW7G ferry@ubuntu-vm
    package_update: true
    package_upgrade: true
    runcmd:
      - systemctl enable ssh
      - systemctl start ssh
      - echo "PermitRootLogin no" >> /etc/ssh/sshd_config
      - echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
      - systemctl restart ssh
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-dv
  namespace: kubevirt
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: ubuntu-vm
  namespace: kubevirt
  labels:
    app: ubuntu-vm
spec:
  domain:
    cpu:
      cores: 1
      model: host-passthrough
    memory:
      guest: 512Mi
    features:
      acpi: {}
      apic: {}
    firmware:
      bootloader:
        efi:
          secureBoot: false
    devices:
      disks:
      - name: rootdisk
        disk:
          bus: virtio
      - name: cloudinit
        cdrom:
          bus: sata
      interfaces:
      - name: default
        masquerade: {}
  networks:
  - name: default
    pod: {}
  volumes:
  - name: rootdisk
    dataVolume:
      name: ubuntu-dv
  - name: cloudinit
    cloudInitNoCloud:
      secretRef:
        name: ubuntu-vm-cloud-init
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh
  namespace: kubevirt
spec:
  type: LoadBalancer
  selector:
    app: ubuntu-vm
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
