apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixos-disk-pvc
  namespace: kubevirt
  labels:
    app: nixos-vm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn
