---
apiVersion: v1
kind: Service
metadata:
  name: nixos-ssh
  namespace: kubevirt
spec:
  type: LoadBalancer
  selector:
    app: nixos
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nixos-ssh-config
  namespace: kubevirt
data:
  ssh_public_key: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7eeqvAb4TGa0E033ml1m5YtwalDMqxwAfBbdG0HW7G ferry@nixos-vm

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: nixos
  namespace: kubevirt
  labels:
    app: nixos
spec:
  running: true
  template:
    metadata:
      labels:
        app: nixos
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: ""
    spec:
      domain:
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: nixos-cloud-v2
