---
apiVersion: v1
kind: Service
metadata:
  name: nixos-ssh
  namespace: kubevirt
spec:
  type: LoadBalancer
  selector:
    app: nixos
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: nixos
  namespace: kubevirt
  labels:
    app: nixos
spec:
  running: true
  template:
    metadata:
      labels:
        app: nixos
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: ""
    spec:
      domain:
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: nixos-cloud
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0:
                dhcp4: true
          userData: |
            #cloud-config
            ssh_pwauth: true
            users:
              - name: root
                lock_passwd: false
                sudo: ALL=(ALL) NOPASSWD:ALL
