fullnameOverride: unifi
image:
  reposory: linuxserver/unifi-controller
  tag: 8.0.24

persistence:
  enabled: true
  storageClass: longhorn
  backup:
    enabled: false

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/protocol: https
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: <path:unifi-config#domain>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - <path:unifi-config#domain>
      secretName: unifi-cert

service:
  type: LoadBalancer
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
  ports:
    devicecom: 8080
    webapi: 8443
  appDiscovery: false
  syslogCapture: false
  loadBalancerTcpIP: <path:unifi-config#loadBalancerTcpIP>
  loadBalancerIP: <path:unifi-config#loadBalancerIP>

