service:
  type: ClusterIP
  port: 8080

# Kubernetes Ingress
ingress:
  enabled: true
  className: traefik

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

  ## Configure the hosts for the ingress
  hosts: 
    - host: <path:ha-config#domain>
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - hosts:
        - <path:ha-config#domain>
      secretName: tls-home-assistant-ingress

persistence:
  enabled: true
  size: 5Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/home-assistant/home-assistant
  tag: "2025.8.0"

configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.42.0.0/16

replicaCount: 1

extraPodSpec:
  initContainers:
    # 1. Download HACS into custom_components
    - name: hacs-init
      image: alpine:3.18
      command:
        - sh
        - -c
        - |
          set -e
          apk add --no-cache bash curl unzip
          mkdir -p /config/custom_components
          wget -O - https://get.hacs.xyz | bash
      volumeMounts:
        - name: config
          mountPath: /config

    # 2. Append HACS token to configuration.yaml if not already present
    - name: hacs-config
      image: alpine:3.18
      command:
        - sh
        - -c
        - |
          set -e
          grep -q '^hacs:' /config/configuration.yaml || \
          echo -e "\nhacs:\n  token: \"<path:ha-config#token>\"" >> /config/configuration.yaml
      volumeMounts:
        - name: config
          mountPath: /config
