---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian
  namespace: obsidian
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app: obsidian
spec:
  ingressClassName: traefik
  rules:
  - host: obsidian-app.hmdev.nl
    http:
      paths:
      - backend:
          service:
            name: obsidian
            port:
              number: 3001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - obsidian-app.hmdev.nl
    secretName: tls-obsidian-ingress
