---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-config
  namespace: obsidian
  labels:
    app: obsidian
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
