image:
  repository: lscr.io/linuxserver/readarr
  tag: "0.4.18.2805"

ingress:
  main:
    enabled: true
    ingressClassName: traefik

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

    hosts: 
      - host: <path:readarr-config#domain>
        paths:
          - path: /
            pathType: ImplementationSpecific

    tls:
      - hosts:
          - <path:readarr-config#domain>
        secretName: tls-readarr-ingress

env:
  TZ: Europe/Amsterdam
  PUID: '1000'
  PGID: '1003'

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1003
  fsGroup: 1003

persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: longhorn
    accessMode: ReadWriteOnce
  media:
    enabled: true
    mountPath: /media
    existingClaim: media-pvc
