ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    - hosts:
        - <path:supabase-config#domain>
      secretName: tls-supabase-ingress
  hosts:
    - host: <path:supabase-config#domain>
      paths:
        - path: /
          pathType: Prefix

persistence:
  db:
    enabled: true
    storageClassName: longhorn
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  storage:
    enabled: true
    storageClassName: longhorn
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  functions:
    enabled: false

deployment:
  analytics:
    enabled: false
  vector:
    enabled: false
  imgproxy:
    enabled: false
  functions:
    enabled: false
  db:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
        ephemeral-storage: 2Gi
  auth:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 512Mi
  kong:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 512Mi
  meta:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 250m
        memory: 256Mi
        ephemeral-storage: 512Mi
  realtime:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 512Mi
  rest:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 250m
        memory: 256Mi
        ephemeral-storage: 512Mi
  storage:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 512Mi
  studio:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 250m
        memory: 256Mi
        ephemeral-storage: 512Mi

environment:
  auth:
    API_EXTERNAL_URL: https://<path:supabase-config#domain>
    GOTRUE_SITE_URL: https://<path:supabase-config#domain>
  studio:
    SUPABASE_PUBLIC_URL: https://<path:supabase-config#domain>
