---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nas-cert
  namespace: nas
spec:
  commonName: <path:nas-config#domain>
  secretName: nas-cert
  dnsNames:
    - <path:nas-config#domain>
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: v1
kind: Service
metadata:
  name: nas-service
  namespace: nas
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas-service
  namespace: nas
subsets:
  - addresses:
      - ip: <path:nas-config#ip>
    ports:
      - port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nas-ingress
  namespace: nas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`<path:nas-config#domain>`)
      kind: Rule
      services:
        - name: nas-service
          kind: Service
          port: 80
  tls:
    secretName: nas-cert
