storageClass:
  create: true
  name: nfs-media
  parameters:
    server: <path:nas-config#domain>
    share: /media
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
  mountOptions:
  - nolock
  - vers=3
