---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
  namespace: unbound
data:
  a-records.conf: |
    # Split-horizon DNS for internal cluster services
    # Resolve git.hmdev.nl to internal Gitea pod IP instead of external IP
    local-zone: "git.hmdev.nl." static
    local-data: "git.hmdev.nl. IN A 10.42.3.46"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: unbound
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: docker.io/mvance/unbound-rpi:1.19.3
        ports:
        - name: svc-53-udp
          containerPort: 53
          protocol: UDP
        - name: svc-53-tcp
          containerPort: 53
          protocol: TCP
        resources:
          limits:
            memory: "300Mi"
            cpu: "250m"
          requests:
            memory: "50Mi"
            cpu: "100m"
        volumeMounts:
        - name: config
          mountPath: /opt/unbound/etc/unbound/a-records.conf
          subPath: a-records.conf
      volumes:
      - name: config
        configMap:
          name: unbound-config

---
kind: Service 
apiVersion: v1 
metadata:
  name: unbound-service 
  namespace: unbound
spec:
  selector:
    app: unbound
  type: ClusterIP
  clusterIP: <path:unbound-config#clusterIp>
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP


