apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claude
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: claude
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/claude
      targetRevision: HEAD
      plugin: {}
  project: default
