apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
spec:
  destination:
    name: in-cluster
    namespace: argocd
  sources:
  - repoURL: 'https://github.com/FrengerH/cluster'
    targetRevision: HEAD
    path: apps/config
  project: default

