apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: hermes
  sources:
  - repoURL: 'https://github.com/FrengerH/cluster'
    targetRevision: HEAD
    path: apps/hermes
  project: default
