apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: home-assistant
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/home-assistant
      targetRevision: HEAD
      plugin: # we just use the plugin source, the plugin script will do the helm pull and template
        env: #set the variables needed 
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "http://pajikos.github.io/home-assistant-helm-chart/"
          - name: HELM_CHART_NAME
            value: "home-assistant"
          - name: HELM_CHART_VERSION
            value: "0.3.14"
          - name: HELM_RELEASE_NAME
            value: "home-assistant"
  project: default

