---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-db
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: immich
  sources:
  - repoURL: 'https://github.com/FrengerH/cluster'
    targetRevision: HEAD
    path: apps/immich-db
  project: default
