apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: kubevirt
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/kubevirt-manifests
      targetRevision: HEAD
  project: default
