apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: kubevirt
  sources:
    - repoURL: 'https://github.com/kubevirt/kubevirt'
      path: deploy
      targetRevision: v1.4.1
  project: default
