apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-operator
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: kubevirt
  sources:
    - repoURL: 'oci://registry.suse.com/edge'
      chart: kubevirt
      targetRevision: 4.11.3
      helm:
        valueFiles:
        - values.yaml
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/kubevirt
      targetRevision: HEAD
  project: default
