apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: kubevirt
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/kubevirt
      targetRevision: HEAD
      plugin:
        env:
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "https://kubevirt.github.io/helm-charts"
          - name: HELM_CHART_NAME
            value: "kubevirt"
          - name: HELM_CHART_VERSION
            value: "1.4.1"
          - name: HELM_RELEASE_NAME
            value: "kubevirt"
  project: default
