apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nixos-server
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: nixos-server
  sources:
    - repoURL: 'https://github.com/FrengerH/cluster'
      path: apps/values/nixos-server
      targetRevision: HEAD
      plugin:
        env:
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "https://frengerh.github.io/nixos-dev"
          - name: HELM_CHART_NAME
            value: "nixos-server"
          - name: HELM_CHART_VERSION
            value: "0.13.0"
          - name: HELM_RELEASE_NAME
            value: "nixos-server"
  project: default
