apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: obsidian
  source:
    repoURL: 'https://github.com/frengerh/cluster'
    path: apps/obsidian
    targetRevision: HEAD
    plugin: {}
  project: default
