apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: pihole
  sources:
  - repoURL: 'https://github.com/FrengerH/cluster'
    targetRevision: HEAD
    path: apps/pihole
  project: default
