---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  destination:
    name: in-cluster
    namespace: pihole
  sources:
  - repoURL: 'https://github.com/FrengerH/cluster'
    targetRevision: HEAD
    path: apps/pihole
  project: default
