apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
spec:
  destination:
    name: in-cluster
    namespace: default
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/reloader
      targetRevision: HEAD
      plugin: # we just use the plugin source, the plugin script will do the helm pull and template
        env: #set the variables needed 
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "https://stakater.github.io/stakater-charts"
          - name: HELM_CHART_NAME
            value: "reloader"
          - name: HELM_CHART_VERSION
            value: "1.2.1"
          - name: HELM_RELEASE_NAME
            value: "reloader"
  project: default

