apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: kube-system
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/sealed-secrets
      targetRevision: HEAD
      plugin: # we just use the plugin source, the plugin script will do the helm pull and template
        env: #set the variables needed 
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "https://bitnami-labs.github.io/sealed-secrets"
          - name: HELM_CHART_NAME
            value: "sealed-secrets"
          - name: HELM_CHART_VERSION
            value: "2.17.1"
          - name: HELM_RELEASE_NAME
            value: "sealed-secrets"
  project: default
