apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
spec:
  destination:
    name: in-cluster
    namespace: supabase
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/supabase
      targetRevision: HEAD
      plugin:
        env:
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "https://supabase-community.github.io/supabase-kubernetes"
          - name: HELM_CHART_NAME
            value: "supabase"
          - name: HELM_CHART_VERSION
            value: "0.5.6"
          - name: HELM_RELEASE_NAME
            value: "supabase"
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
