apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: arr-stack
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/transmission
      targetRevision: HEAD
      plugin: # we just use the plugin source, the plugin script will do the helm pull and template
        env: #set the variables needed 
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "https://nicholaswilde.github.io/helm-charts/"
          - name: HELM_CHART_NAME
            value: "transmission"
          - name: HELM_CHART_VERSION
            value: "0.2.19"
          - name: HELM_RELEASE_NAME
            value: "transmission"
  project: default

