apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vms
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
  destination:
    name: in-cluster
    namespace: kubevirt
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/vms
      targetRevision: HEAD
  project: default
