apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
spec:
  destination:
    name: in-cluster
    namespace: wireguard
  sources:
    - repoURL: 'https://github.com/frengerh/cluster'
      path: apps/values/wireguard
      targetRevision: HEAD
      plugin: # we just use the plugin source, the plugin script will do the helm pull and template
        env: #set the variables needed 
          - name: HELM_VALUES_FILES
            value: "values.yaml"
          - name: HELM_REPO_URL
            value: "https://freifunkMUC.github.io/wg-access-server-chart"
          - name: HELM_CHART_NAME
            value: "wg-access-server"
          - name: HELM_CHART_VERSION
            value: "1.0.0"
          - name: HELM_RELEASE_NAME
            value: "wireguard"
  project: default


