service:
  type: ClusterIP
  port: 6052

# Kubernetes Ingress
ingress:
  enabled: true
  className: traefik

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

  ## Configure the hosts for the ingress
  hosts: 
    - host: <path:esphome-config#domain>
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - hosts:
        - <path:esphome-config#domain>
      secretName: tls-home-assistant-ingress

persistence:
  enabled: true
  size: 1Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce

image:
  repository: ghcr.io/esphome/esphome
  tag: "2025.6.3"

replicaCount: 1

