ingress:
  enabled: true
  ingressClassName: traefik

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

  hosts: 
    - host: <path:jellyseer-config#domain>
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - hosts:
        - <path:jellyseer-config#domain>
      secretName: tls-jellyseer-ingress

# env:
#   TZ: Europe/Amsterdam
  # PUID: '1000'
  # PGID: '1003'

config:
  persistence:
    size: 5Gi
    storageClass: longhorn
    accessMode: ReadWriteOnce
