env:
  TZ: "Europe/Amsterdam"
  PUID: '1000'
  PGID: '1003'
  WEBUI_PORT: '8080'
  TORRENTING_PORT: '8989'

# ingress:
#   enabled: true
#   className: traefik

#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/service: qbittorrent
#     traefik.ingress.kubernetes.io/service-port: "8989"
#     traefik.ingress.kubernetes.io/router.tls: "true"

#   hosts:
#     - host: <path:qbittorrent-config#domain>
#       paths:
#         - path: /
#           pathType: ImplementationSpecific

#   tls:
#     - hosts:
#       - <path:qbittorrent-config#domain>
#       secretName: tls-qbittorrent-ingress

persistence:
  media:
    enabled: true
    existingClaim: media-pvc
  config:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 10Gi
